name: mowerless labour
favicon: null
layout_spectrum: 0.6247566412203014
typography_spectrum: 0.2669639834202826
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#050426'
    - '#81b16b'
    - '#303144'
    - '#516c4f'
    - '#fbedf6'
  brandStrength: 0.75
  lightness: 0.8915659436024725
  saturation: 0.25
  rhythmicContrast: 0.25
purpose: []
