name: mowerless labour
favicon: null
layout_spectrum: 0.82927
typography_spectrum: 0.48808
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ecf6f8'
    - '#ed1f2b'
    - '#1c489f'
    - '#eb747b'
    - '#96abcf'
  brandStrength: 0.6875
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
